[general]
import = [ 
  "./themes/catppuccin_macchiato.toml"
]

# Window dimensions
[window]
dimensions.columns = 100
dimensions.lines = 30
position.x = 0
position.y = 0
padding.x = 5
padding.y = 5
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true  # Títulos dinâmicos baseados no conteúdo
decorations_theme_variant = "Dark"  # Adapta-se ao tema do sistema

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"
size = 13.0
offset.x = 1
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
action = "Quit"

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true
blink_interval = 750

# Shell
 [terminal.shell]
program = "/usr/bin/tmux"
# program = "/usr/bin/fish"
args = ["new-session"]
# args = ["--login"]

# Environmen
[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

